name: build
on:
  push:
    branches:
      - '!main'
  pull_request:
    branches:
      - '**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
      name: Check out code
    -
      uses: mr-smithers-excellent/docker-build-push@v5
      name: Build Docker image
      with:
        image: nginx
        tags: latest
        pushImage: false
        registry: docker.io
        dockerfile: Dockerfile